[build]
# We place build outputs in the `build` directory in the root of this project.
# This directory will contain build outputs for both the Angular frontend and
# the binary built by Tauri.
target-dir = 'build/desktop'

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]

[net]
git-fetch-with-cli = true
